logging.level.root: TRACE

fina:
  keystore:
    path: 'classpath:${secrets.keystore.filename}'
    storepass: '${secrets.keystore.pass}'
    alias: '${secrets.keystore.alias}'
    keypass: '${secrets.keystore.pass}'

spring:
  application.name: fiskalizacija
  profiles:
    active: secrets
